# Generated by Django 5.2.17 on 2026-09-24 21:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import monitoring.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECEIVED', 'Заявление принято'), ('IN_REVIEW', 'На рассмотрении'), ('INSPECTION_SCHEDULED', 'Назначен выезд инспектора'), ('COMPLETED', 'Завершено'), ('REJECTED', 'Отклонено')], default='RECEIVED', max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('owner_telegram_user_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='TrackingSequence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_inspector', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RECEIVED', 'Заявление принято'), ('IN_REVIEW', 'На рассмотрении'), ('INSPECTION_SCHEDULED', 'Назначен выезд инспектора'), ('COMPLETED', 'Завершено'), ('REJECTED', 'Отклонено')], max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitoring.application')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=30)),
                ('key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'key'), name='idempotency_service_key')],
            },
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cadastral_number', models.CharField(max_length=100, unique=True)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('purpose', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('geometry', models.JSONField(blank=True, null=True, validators=[monitoring.validators.validate_geometry])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('area_ha__gt', 0)), name='plot_positive_area')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('DUMPING', 'Свалка'), ('LAND_GRAB', 'Самозахват'), ('UNUSED_LAND', 'Неиспользуемая земля'), ('ABANDONED_PLOT', 'Заброшенный участок'), ('OTHER', 'Другое')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('INSPECTION', 'На проверке'), ('VIOLATION', 'Нарушение подтверждено'), ('IN_PROGRESS', 'Устраняется'), ('RESOLVED', 'Закрыто')], default='NEW', max_length=20)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='monitoring.landplot')),
                ('tracking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='monitoring.trackingrecord')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='tracking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='monitoring.trackingrecord'),
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_file_id', models.CharField(max_length=1024)),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='monitoring.report')),
            ],
            options={
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('report', 'ordinal'), name='photo_report_ordinal')],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated')], max_length=10)),
                ('before', models.JSONField(null=True)),
                ('after', models.JSONField()),
                ('comment', models.TextField(null=True)),
                ('actor_type', models.CharField(max_length=12)),
                ('actor_label', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitoring.report')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['report', 'created_at', 'id'], name='monitoring__report__9e9d31_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='monitoring__status_531045_idx'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='report_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='report_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='report_positive_version'),
        ),
    ]
