import { ArrowDownIcon } from '@phosphor-icons/react/dist/csr/ArrowDown';
import { ArrowDownLeftIcon } from '@phosphor-icons/react/dist/csr/ArrowDownLeft';
import { ArrowRightIcon } from '@phosphor-icons/react/dist/csr/ArrowRight';
import { ArrowUpIcon } from '@phosphor-icons/react/dist/csr/ArrowUp';
import { ArrowUpRightIcon } from '@phosphor-icons/react/dist/csr/ArrowUpRight';
import { CalendarDotsIcon } from '@phosphor-icons/react/dist/csr/CalendarDots';
import { ChartLineUpIcon } from '@phosphor-icons/react/dist/csr/ChartLineUp';
import { CheckIcon } from '@phosphor-icons/react/dist/csr/Check';
import { ChecksIcon } from '@phosphor-icons/react/dist/csr/Checks';
import { CaretRightIcon } from '@phosphor-icons/react/dist/csr/CaretRight';
import { QuestionIcon } from '@phosphor-icons/react/dist/csr/Question';
import { ClockIcon } from '@phosphor-icons/react/dist/csr/Clock';
import { DownloadSimpleIcon } from '@phosphor-icons/react/dist/csr/DownloadSimple';
import { EyeIcon } from '@phosphor-icons/react/dist/csr/Eye';
import { EyeSlashIcon } from '@phosphor-icons/react/dist/csr/EyeSlash';
import { FileTextIcon } from '@phosphor-icons/react/dist/csr/FileText';
import { ImageBrokenIcon } from '@phosphor-icons/react/dist/csr/ImageBroken';
import { InfoIcon } from '@phosphor-icons/react/dist/csr/Info';
import { StackSimpleIcon } from '@phosphor-icons/react/dist/csr/StackSimple';
import { StackIcon } from '@phosphor-icons/react/dist/csr/Stack';
import { ListBulletsIcon } from '@phosphor-icons/react/dist/csr/ListBullets';
import { CircleNotchIcon } from '@phosphor-icons/react/dist/csr/CircleNotch';
import { CrosshairSimpleIcon } from '@phosphor-icons/react/dist/csr/CrosshairSimple';
import { SignOutIcon } from '@phosphor-icons/react/dist/csr/SignOut';
import { MapTrifoldIcon } from '@phosphor-icons/react/dist/csr/MapTrifold';
import { MapPinIcon } from '@phosphor-icons/react/dist/csr/MapPin';
import { MapPinAreaIcon } from '@phosphor-icons/react/dist/csr/MapPinArea';
import { ChatTextIcon } from '@phosphor-icons/react/dist/csr/ChatText';
import { MinusIcon } from '@phosphor-icons/react/dist/csr/Minus';
import { PlusIcon } from '@phosphor-icons/react/dist/csr/Plus';
import { BroadcastIcon } from '@phosphor-icons/react/dist/csr/Broadcast';
import { ArrowsClockwiseIcon } from '@phosphor-icons/react/dist/csr/ArrowsClockwise';
import { ArrowCounterClockwiseIcon } from '@phosphor-icons/react/dist/csr/ArrowCounterClockwise';
import { FloppyDiskIcon } from '@phosphor-icons/react/dist/csr/FloppyDisk';
import { ScanIcon } from '@phosphor-icons/react/dist/csr/Scan';
import { MagnifyingGlassIcon } from '@phosphor-icons/react/dist/csr/MagnifyingGlass';
import { SlidersHorizontalIcon } from '@phosphor-icons/react/dist/csr/SlidersHorizontal';
import { ChatTeardropDotsIcon } from '@phosphor-icons/react/dist/csr/ChatTeardropDots';
import { StopIcon } from '@phosphor-icons/react/dist/csr/Stop';
import { WarningIcon } from '@phosphor-icons/react/dist/csr/Warning';
import { XIcon } from '@phosphor-icons/react/dist/csr/X';

// Keep one visual style and accessibility default across all interface icons.
function roundedIcon(Component, weight = 'duotone') {
  return function RoundedIcon(props) {
    return <Component size={24} weight={weight} aria-hidden="true" focusable="false" {...props} />;
  };
}

export const ArrowDown = roundedIcon(ArrowDownIcon, 'regular');
export const ArrowDownLeft = roundedIcon(ArrowDownLeftIcon, 'regular');
export const ArrowRight = roundedIcon(ArrowRightIcon, 'regular');
export const ArrowUp = roundedIcon(ArrowUpIcon, 'regular');
export const ArrowUpRight = roundedIcon(ArrowUpRightIcon, 'regular');
export const CalendarDays = roundedIcon(CalendarDotsIcon);
export const ChartNoAxesCombined = roundedIcon(ChartLineUpIcon);
export const Check = roundedIcon(CheckIcon, 'regular');
export const CheckCheck = roundedIcon(ChecksIcon, 'regular');
export const ChevronRight = roundedIcon(CaretRightIcon, 'regular');
export const CircleHelp = roundedIcon(QuestionIcon);
export const Clock3 = roundedIcon(ClockIcon);
export const Download = roundedIcon(DownloadSimpleIcon);
export const Eye = roundedIcon(EyeIcon);
export const EyeOff = roundedIcon(EyeSlashIcon);
export const FileText = roundedIcon(FileTextIcon);
export const ImageOff = roundedIcon(ImageBrokenIcon);
export const Info = roundedIcon(InfoIcon);
export const Layers = roundedIcon(StackSimpleIcon);
export const Layers3 = roundedIcon(StackIcon);
export const List = roundedIcon(ListBulletsIcon);
export const LoaderCircle = roundedIcon(CircleNotchIcon, 'regular');
export const LocateFixed = roundedIcon(CrosshairSimpleIcon);
export const LogOut = roundedIcon(SignOutIcon);
export const Map = roundedIcon(MapTrifoldIcon);
export const MapPin = roundedIcon(MapPinIcon);
export const MapPinned = roundedIcon(MapPinAreaIcon);
export const MessageSquare = roundedIcon(ChatTextIcon);
export const Minus = roundedIcon(MinusIcon, 'regular');
export const MoveUpRight = roundedIcon(ArrowUpRightIcon, 'regular');
export const Plus = roundedIcon(PlusIcon, 'regular');
export const Radio = roundedIcon(BroadcastIcon);
export const RefreshCw = roundedIcon(ArrowsClockwiseIcon, 'regular');
export const RotateCcw = roundedIcon(ArrowCounterClockwiseIcon, 'regular');
export const Save = roundedIcon(FloppyDiskIcon);
export const ScanLine = roundedIcon(ScanIcon);
export const Search = roundedIcon(MagnifyingGlassIcon);
export const SlidersHorizontal = roundedIcon(SlidersHorizontalIcon);
export const AssistantChat = roundedIcon(ChatTeardropDotsIcon);
export const Square = roundedIcon(StopIcon);
export const TriangleAlert = roundedIcon(WarningIcon);
export const X = roundedIcon(XIcon, 'regular');
